---
abstract: 'Time different perls for certain tasks'
author:
  - unknown
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.66, CPAN::Meta::Converter version 2.132830'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: perlbench
no_index:
  directory:
    - benchmarks
    - perlbench-results
    - t
  package:
    - Pod::HTML
requires:
  Cwd: 0
  File::Basename: 0
  File::Path: 0
  Getopt::Std: 0
  Sys::Hostname: 0
  Time::HiRes: 0
resources:
  repository: https://github.com/briandfoy/perlbench
version: 0.96
